import puppeteer from 'puppeteer';
import 'dotenv/config';
const SUP=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const SP="/private/tmp/claude-501/-Users-chris-RGA-Rocket-Growth-Agency-Website-VS-Code/c82fa8f6-965d-4613-89b3-b14fb8343738/scratchpad";
const r=await fetch(`${SUP}/auth/v1/admin/generate_link`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({type:'magiclink',email:'hello@rocketgrowthagency.com',redirect_to:'https://www.rocketgrowthagency.com/admin/'})});
const j=await r.json();const link=j.action_link||j.properties?.action_link;
const b=await puppeteer.launch({headless:'new',args:['--no-sandbox','--window-size=1500,2200']});const p=await b.newPage();
await p.setViewport({width:1500,height:2200,deviceScaleFactor:1});
p.on('pageerror',e=>console.log('PAGEERR:',String(e).slice(0,200)));
await p.goto(link,{waitUntil:'networkidle2',timeout:60000});
await new Promise(z=>setTimeout(z,7000));
const info=await p.evaluate(()=>{
  const txt=document.body.innerText.slice(0,600);
  const views=[...document.querySelectorAll('[id]')].filter(e=>!e.hidden&&/view|panel|dashboard|pipeline|client/i.test(e.id)).map(e=>e.id).slice(0,15);
  const rgaEls=[...document.querySelectorAll('*')].filter(e=>e.children.length===0&&/Rocket Growth Agency/.test(e.textContent)).length;
  return {txt,views,rgaEls,url:location.href};
});
console.log(JSON.stringify(info,null,1).slice(0,1200));
await p.screenshot({path:SP+'/vp_admin_landing.png'});
await b.close();
