// Per-step actor classification + client-facing labels.
// Used by the playbook export script to produce JSON consumed by admin + portal.
//
// actor values:
//   "rga"    — RGA team executes (server-side or admin runs)
//   "client" — Client must do (no RGA involvement possible)
//   "both"   — Hybrid: RGA leads/drafts, client must attend/approve/provide
//
// Steps with actor="client" or "both" appear in the portal "Action Items" checklist.
// Steps with actor="rga" or "both" appear in admin Month 1 / Month 2+ tabs.

export const ACTOR_MAP = {
  // ===== MONTH 1 =====
  "m1.kickoff.create":       { actor: "rga" },
  "m1.kickoff.call":         { actor: "both", clientLabel: "Attend kickoff call with RGA",                 clientHint: "30-min Zoom — we walk through the plan + what we need from you. RGA leads.", clientForm: null },
  "m1.access.password_manager":{ actor: "rga" },
  "m1.access.gbp":           { actor: "both", clientLabel: "Add RGA as Manager on your Google Business Profile", clientHint: "Open business.google.com → Settings → People & Access → Add user → chris@rocketgrowthagency.com → Role: Manager", clientForm: "oauth_grant" },
  "m1.access.analytics":     { actor: "both", clientLabel: "Grant RGA access to Google Analytics (or skip if you don't have GA4 yet)", clientHint: "If you have GA4, grant Administrator access. If not, RGA installs in week 1.", clientForm: "oauth_grant" },
  "m1.access.search_console":{ actor: "both", clientLabel: "Grant RGA access to Search Console (or skip if not set up)", clientHint: "If you have Search Console, grant Owner access. If not, RGA verifies your domain in week 1.", clientForm: "oauth_grant" },
  "m1.access.website":       { actor: "client", clientLabel: "Provide your website CMS login", clientHint: "WordPress / Wix / Shopify admin login. Send via secure share link, NOT email.", clientForm: "generic" },
  "m1.tracking.call_setup":  { actor: "both",   clientLabel: "Decide on call tracking (CallRail / OpenPhone / Skip)", clientHint: "Phone calls are 50-70% of leads for service businesses. Tracking ($25-45/mo) lets us measure calls from Google. Skipping is fine — your reports just won't include phone-call KPIs.", clientForm: "generic" },
  "m1.tracking.form_setup":  { actor: "both",   clientLabel: "Allow form tracking on your website", clientHint: "Lets us measure leads coming through your contact form. Free if you have GA4. Requires CMS access (we install).", clientForm: "generic" },
  "m1.audit.gbp_baseline":   { actor: "rga" },
  "m1.audit.website":        { actor: "rga" },
  "m1.audit.competitors":    { actor: "rga" },
  "m1.strategy.keywords_locations": { actor: "both", clientLabel: "Confirm your top 5 keywords + 3 sub-locations to target", clientHint: "RGA suggests based on data — you confirm or override.", clientForm: "generic" },
  "m1.audit.grid_baseline":  { actor: "rga" },
  "m1.audit.kpi_baseline":   { actor: "rga" },
  "m1.audit.citations":      { actor: "rga" },
  "m1.gbp.verify":           { actor: "client", clientLabel: "Verify your Google Business Profile (if not already)", clientHint: "Verification by postcard takes 5-14 days; video and phone are faster if eligible. Open GBP → click Verify.", clientForm: "generic" },
  "m1.gbp.optimize_categories":{ actor: "rga" },
  "m1.gbp.services_products":{ actor: "rga" },
  "m1.gbp.business_description":{ actor: "rga" },
  "m1.gbp.photos":           { actor: "both", clientLabel: "Provide 20+ business photos (logo, team, work, equipment)", clientHint: "Upload via the form. We push them to your GBP automatically. Better photos = better rankings.", clientForm: "photo_upload" },
  "m1.gbp.hours_attributes": { actor: "both", clientLabel: "Confirm your business hours + special attributes", clientHint: "Tell us your weekly hours, holiday closures, and which attributes apply (woman/veteran-owned, accessibility, payment methods, etc).", clientForm: "generic" },
  "m1.gbp.messaging":        { actor: "both", clientLabel: "Turn on GBP messaging", clientHint: "Lets potential customers text you directly from Google. RGA writes the welcome message; you toggle it on.", clientForm: "generic" },
  "m1.gbp.booking_link":     { actor: "both", clientLabel: "Set up online booking (Calendly or website form)", clientHint: "Customers can book directly from Google search. RGA helps you pick a tool.", clientForm: "generic" },
  "m1.gbp.attributes":       { actor: "both", clientLabel: "Confirm GBP attributes (women/veteran-owned, accessibility, etc)", clientHint: "Walk through the checklist with us — most businesses miss 60%+ of attributes.", clientForm: "generic" },
  "m1.gbp.qa_seed":          { actor: "both", clientLabel: "Post 8 Q&A pairs to your GBP from your personal account", clientHint: "RGA drafts the questions + answers. You post the questions from your personal Google account, then we answer from the business profile.", clientForm: "generic" },
  "m1.web.homepage_meta":    { actor: "rga" },
  "m1.web.h1_cta":           { actor: "rga" },
  "m1.web.nap_consistency":  { actor: "rga" },
  "m1.web.schema":           { actor: "rga" },
  "m1.web.tracking":         { actor: "rga" },
  "m1.web.priority_pages":   { actor: "rga" },
  "m1.web.location_pages":   { actor: "rga" },
  "m1.web.blog_seed":        { actor: "rga" },
  "m1.web.image_seo":        { actor: "rga" },
  "m1.web.internal_linking": { actor: "rga" },
  "m1.web.core_web_vitals":  { actor: "rga" },
  "m1.web.expanded_schema":  { actor: "rga" },
  "m1.cit.priority_top10":   { actor: "rga" },
  "m1.cit.industry_specific":{ actor: "rga" },
  "m1.platform.bing_apple":  { actor: "rga" },
  "m1.gbp.knowledge_panel":  { actor: "rga" },
  "m1.web.service_location_matrix": { actor: "rga" },
  "m1.web.https_sitemap":    { actor: "rga" },
  "m1.brand.youtube_setup":  { actor: "rga" },
  "m1.review.system":        { actor: "rga" },
  "m1.review.first_5":       { actor: "both", clientLabel: "Send personalized review requests to 5 past customers", clientHint: "RGA drafts a personal text from you. You send it to 5 happy past customers. Goal: 5 4★+ reviews live by week 3.", clientForm: "generic" },
  "m1.review.response":      { actor: "rga" },
  "m1.report.month1":        { actor: "rga" },
  "m1.call.close":           { actor: "both", clientLabel: "Attend Month 1 close-out call", clientHint: "30-min Zoom — RGA walks through your Month 1 report + plan for Month 2.", clientForm: null },
  "m1.handoff.month2":       { actor: "rga" },

  // ===== MONTH 2+ =====
  "m2.snap.rank_tracker":    { actor: "rga" },
  "m2.snap.grid_scan":       { actor: "rga" },
  "m2.snap.gbp_metrics":     { actor: "rga" },
  "m2.snap.gsc_metrics":     { actor: "rga" },
  "m2.snap.ga4_metrics":     { actor: "rga" },
  "m2.snap.competitors":     { actor: "rga" },
  "m2.snap.business_outcomes":{ actor: "both", clientLabel: "Submit this month's business numbers (leads, calls, revenue)", clientHint: "5-min form — gives us the full picture for your monthly report.", clientForm: "generic" },
  "m2.plan.rotating_focus":  { actor: "rga" },
  "m2.plan.tasks_for_month": { actor: "rga" },
  "m2.exec.gbp_posts":       { actor: "rga" },
  "m2.exec.gbp_photos":      { actor: "both", clientLabel: "Upload 5+ new photos this month", clientHint: "Recent jobs, team, equipment. We push to GBP automatically.", clientForm: "photo_upload" },
  "m2.exec.review_push":     { actor: "both", clientLabel: "Submit this week's customer list for review requests", clientHint: "Paste names + phones for customers you served this week. We auto-send personalized review requests.", clientForm: "customer_list" },
  "m2.exec.review_responses":{ actor: "rga" },
  "m2.exec.focus_area_work": { actor: "rga" },
  "m2.exec.brand_mentions":  { actor: "rga" },
  "m2.exec.local_pr":        { actor: "rga" },
  "m2.exec.competitor_backlink_steal": { actor: "rga" },
  "m2.exec.haro_pitches":    { actor: "rga" },
  "m2.exec.youtube_video":   { actor: "both", clientLabel: "Record monthly YouTube video (we'll send the script)", clientHint: "60-90 sec, phone OK. RGA writes the script + handles upload. You're the on-camera talent.", clientForm: "generic" },
  "m2.exec.cannibalization_audit": { actor: "rga" },
  "m2.exec.site_audit_recurring":  { actor: "rga" },
  "m2.exec.gbp_attributes_refresh":{ actor: "rga" },
  "m2.exec.mystery_shop":    { actor: "rga" },
  "m2.report.generate":      { actor: "rga" },
  "m2.report.deliver":       { actor: "rga" },
  "m2.call.monthly":         { actor: "both", clientLabel: "Attend monthly check-in call", clientHint: "20-30 min Zoom — RGA walks through your monthly report + next focus area.", clientForm: null },
  "m2.win_story.capture":    { actor: "both", clientLabel: "Share one customer win story this month", clientHint: "5-min form — we use your stories for case studies, GBP posts, and social proof.", clientForm: "generic" },
  "m2.handoff.next_month":   { actor: "rga" },
};
