const { default: p } = await import("puppeteer");
const U=process.env.SUPABASE_URL,K=process.env.SUPABASE_SERVICE_ROLE_KEY;
const cid=(await (await fetch(`${U}/rest/v1/clients?archived_at=is.null&select=id&limit=1`,{headers:{apikey:K,Authorization:`Bearer ${K}`}})).json())[0].id;
const j=await (await fetch(`${U}/auth/v1/admin/generate_link`,{method:"POST",headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json"},body:JSON.stringify({type:"magiclink",email:"hello@rocketgrowthagency.com"})})).json();
const b=await p.launch({headless:"new",args:["--no-sandbox"]});
const pg=await b.newPage(); await pg.setViewport({width:1150,height:1200,deviceScaleFactor:2});
await pg.goto(j.action_link||j.properties.action_link,{waitUntil:"networkidle2",timeout:60000});
await new Promise(r=>setTimeout(r,6000));
await pg.goto(`https://www.rocketgrowthagency.com/admin/?view=client&id=${cid}&tab=onboarding-v2`,{waitUntil:"networkidle2",timeout:60000});
await new Promise(r=>setTimeout(r,15000));
await pg.evaluate(()=>{ const ph=[...document.querySelectorAll(".ob-phase")].find(x=>/Access/.test(x.querySelector(".ob-ph-name")?.textContent||""));
  if(ph && !ph.classList.contains("open")) ph.querySelector("[data-ob-phase-toggle]")?.click(); });
await new Promise(r=>setTimeout(r,1200));
await pg.evaluate(()=>{ document.querySelectorAll("details.ob-out:not([open]) > summary").forEach(x=>x.click()); });
await new Promise(r=>setTimeout(r,1200));
const el=await pg.evaluateHandle(()=>[...document.querySelectorAll(".ob-step.done")].find(s=>/secure access vault/.test(s.textContent)));
const e=el.asElement(); if(e) await e.screenshot({path:"/Users/chris/Desktop/admin-step5-output.png"});
console.log("  captured step 5");
await b.close();
